# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=42, verbose_name='Имя задачи')),
                ('discription', models.TextField(max_length=700, null=True, verbose_name='Описание задачи')),
                ('tags', models.JSONField(null=True, verbose_name='Теги')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
            ],
        ),
    ]
