# Generated by Django 6.0.3 on 2026-04-03 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(choices=[(0, 'Активная'), (1, 'В процессе'), (2, 'Выполнена'), (3, 'Провалена'), (4, 'Отложена')], default=0, verbose_name='Прогресс'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.TextField(choices=[('work', 'Работа'), ('home', 'Дом'), ('my_tasks', 'Мои задачи')], null=True, verbose_name='Теги'),
        ),
    ]
